api:
  addr: 0.0.0.0
  port: 8080

tracing:
  service-name: rusty-accounts
  otlp-exporter-endpoint: http://localhost:4317

pg-config:
  host: localhost
  port: 5432
  user: rusty-accounts
  password: rusty-accounts
  dbname: rusty-accounts
  sslmode: prefer

evt-log:
  server-addr: localhost:4222
  setup: true
